name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86-android, x86_64-android, x86-linux, x86_64-linux]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install gcc-multilib -y
          sudo apt install dos2unix -y
          git clone https://github.com/LuaJIT/LuaJIT luajit
          sudo chmod -R 777 *
          dos2unix build.sh
      - name: Build
        run: ./build.sh ${{matrix.arch}}
      - uses: actions/upload-artifact@v2
        with:
          name: libyaml-${{matrix.arch}}
          path: luajit/src/libluajit.a